project:
  type: website
  output-dir: docs

website:
  title: "MGTA_495 Xiaoran's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
